// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTHkOe6A25w1In4sLsj4-_1_O8z7xMzM0',
    appId: '1:85280830050:web:6892f6a8958982f254973b',
    messagingSenderId: '85280830050',
    projectId: 'urlife-6b1cc',
    authDomain: 'urlife-6b1cc.firebaseapp.com',
    databaseURL: 'https://urlife-6b1cc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'urlife-6b1cc.appspot.com',
    measurementId: 'G-QLJ6HRGWPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx0Bp06cSaY5WL7P1xbY0pidXm05Ew9zY',
    appId: '1:85280830050:android:f908df1cadc2572054973b',
    messagingSenderId: '85280830050',
    projectId: 'urlife-6b1cc',
    databaseURL: 'https://urlife-6b1cc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'urlife-6b1cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmSckBYUFyPrlVsCcx02bEG7S8ESMPnJ4',
    appId: '1:85280830050:ios:59e32eb1dff0f4ff54973b',
    messagingSenderId: '85280830050',
    projectId: 'urlife-6b1cc',
    databaseURL: 'https://urlife-6b1cc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'urlife-6b1cc.appspot.com',
    androidClientId: '85280830050-0p6iop7rdeka5rcsamdcm66ks4hscdj1.apps.googleusercontent.com',
    iosClientId: '85280830050-5tfdlbofbtrr09defdj33rgq3is93abo.apps.googleusercontent.com',
    iosBundleId: 'com.example.membership',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmSckBYUFyPrlVsCcx02bEG7S8ESMPnJ4',
    appId: '1:85280830050:ios:59e32eb1dff0f4ff54973b',
    messagingSenderId: '85280830050',
    projectId: 'urlife-6b1cc',
    databaseURL: 'https://urlife-6b1cc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'urlife-6b1cc.appspot.com',
    androidClientId: '85280830050-0p6iop7rdeka5rcsamdcm66ks4hscdj1.apps.googleusercontent.com',
    iosClientId: '85280830050-5tfdlbofbtrr09defdj33rgq3is93abo.apps.googleusercontent.com',
    iosBundleId: 'com.example.membership',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIyCS11b-hhpHFbDF5QNe626oEBz8UJxg',
    appId: '1:85280830050:web:98c0b55887e3373d54973b',
    messagingSenderId: '85280830050',
    projectId: 'urlife-6b1cc',
    authDomain: 'urlife-6b1cc.firebaseapp.com',
    databaseURL: 'https://urlife-6b1cc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'urlife-6b1cc.appspot.com',
    measurementId: 'G-0B4YGML9SY',
  );

}